# Generated by Django 5.2.5 on 2026-03-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_seat_is_reserved_seat_reserved_at_seat_reserved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_reserved',
        ),
    ]
